version: '3'
services:
  nginx:
    build:
       dockerfile: ./Dockerfilenginx
       context: .
    image: marlonsevero/nginx
    container_name: nginx
    ports:
      - "5555:80"
    networks:
      - redelocal
    depends_on:
      - "web1"
      - "web2"
      - "web3"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"   # Interface Web
      - "50000:50000" # Comunicação com agentes
  db:
    build:
      dockerfile: ./Dockerfiledb
      context: .
    image: marlonsevero/db
    container_name: db
    networks:
      - redelocal
    ports: 
      - "3306"

  web1:
    build:
       dockerfile: ./Dockerfileweb
       context: .
    image: marlonsevero/web
    container_name: web1
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web2: 
    image: marlonsevero/web
    container_name: web2
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web3: 
    image: marlonsevero/web
    container_name: web3
    ports:
      - "80"
    networks:
      - redelocal 
    depends_on:
      - "db"  
    
networks:
  redelocal:
    driver: bridge
